
services:
    frontend:
        build:
            context: "./"
            dockerfile: "./frontend/Dockerfile"
        environment:
            FRONTEND_PORT: ${FRONTEND_PORT}
        ports:
            - ${FRONTEND_PORT_PUBLIC}:${FRONTEND_PORT}
        profiles: [dev]
    backend:
        build:
            context: "./"
            dockerfile: "./backend/Dockerfile"
            target: ${TARGET}
        environment:
            BACKEND_PORT: ${BACKEND_PORT}
        ports:
            - ${BACKEND_PORT_PUBLIC}:${BACKEND_PORT}
