
services:
    mqtt-broker:
        build:
            context: "./"
            dockerfile: "./mqtt-broker/Dockerfile"
            target: ${TARGET}
            args:
                MQTT_ADMIN_USERNAME: ${MQTT_ADMIN_USERNAME}
                MQTT_ADMIN_PASSWORD: ${MQTT_ADMIN_PASSWORD}
        ports:
            - ${MQTT_BROKER_PORT_PUBLIC}:${MQTT_BROKER_PORT}
    reverse-proxy:
        build:
            context: "./"
            dockerfile: "./reverse-proxy/Dockerfile"
            target: ${TARGET}
            args:
                REVERSE_PROXY_CRT: ${REVERSE_PROXY_CRT}
                REVERSE_PROXY_KEY: ${REVERSE_PROXY_KEY}
        ports:
            - ${REVERSE_PROXY_PORT_PUBLIC}:${REVERSE_PROXY_PORT}
        depends_on:
            - backend
    backend:
        build:
            context: "./"
            dockerfile: "./backend/Dockerfile"
            target: ${TARGET}
        environment:
            BACKEND_PORT: ${BACKEND_PORT}

