
services:
    reverse-proxy:
        build:
            context: "./"
            dockerfile: "./reverse-proxy/Dockerfile"
            target: ${TARGET}
        ports:
            - ${REVERSE_PROXY_PORT_PUBLIC}:${REVERSE_PROXY_PORT}
        depends_on:
            - backend
    backend:
        build:
            context: "./"
            dockerfile: "./backend/Dockerfile"
            target: ${TARGET}
        environment:
            BACKEND_PORT: ${BACKEND_PORT}

